name: Generate 120 UA

on:
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  build:
    name: Run

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install exrex
    - name: Generate UA
      run: |
        cd ./.github/
        python generate-user-agents.py
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generated User Agents

        file_pattern: const.py
